#! /bin/bash
#
# Copyright © 2001 - 2012 Denis Salmanovich denis.salmanovich@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

[ -f /etc/denix-colors ] && . /etc/denix-colors

# Check if script runs under root
if ! [ "$(whoami)" = "root" ]; then
    echo "You have to run me with root user priveleges!"
    exit 1
fi

# Check CPU virtualization flag
if ! egrep '(vmx|svm)' /proc/cpuinfo >/dev/null 2>&1; then
    echo "W A R N I N G"
    echo "_____________"
    echo "Your CPU not supporting KVM!"
    echo "Only QEMU will be available."
    echo -n "Do you want to continue the installation? (Y/n)?"; read USERINPUT
    if [ "${USERINPUT}" = "n" -o "${USERINPUT}" = "N" ]; then
	exit 0
    fi
else
    echo "CPU with supported virtualization flag found!"
fi

# Install kvm packages
pk="qemu-kvm libvirt-daemon-kvm virt-manager libvirt qemu kvm"
for i in $pk; do
    if ! rpm -q $i >/dev/null 2>&1; then
	required_packages="$required_packages $i"
    fi
done

if ! [ "$required_packages" = "" ]; then
	$color_Purple
	echo "Some packages not found on your system. Trying to download and install..."
	if ! yum -y install $required_packages; then
	    $color_BRed
	    echo "Download failed! Check internet connection and try again!"
	    $color_Off
	    exit 1
	else
	    $color_Green
	    echo "Installation success!"
	    $color_Off
	fi
fi

# Enable daemons
chkconfig libvirtd on

# Start daemons
service libvirtd start

# Create installation signature
if ! [ -d /var/lib/system-setup-tools ]; then
	install -d /var/lib/system-setup-tools
fi
echo "Install date: `date`" > /var/lib/system-setup-tools/kvm

$color_BGreen
echo "Setup completed!"
$color_Off
