#! /bin/bash
#
# Copyright © 2001 - 2012 Denis Salmanovich denis.salmanovich@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

[ -f /etc/denix-colors ] && . /etc/denix-colors

# Check if script runs under root
if ! [ "$(whoami)" = "root" ]; then
    echo "You have to run me with root user priveleges!"
    exit 1
fi

found_user=`cat /etc/passwd | awk -F':' '$3 >999' | grep '/bin/bash' | awk -F':' '{print $1}' | head -1`

while [ "${auto_login}" = "" ]; do
    echo -n "Enter username for autologin [${found_user}]: "; read auto_login
    if [ "${auto_login}" = "" ]; then
	auto_login="${found_user}"
    fi
    
done


result=`cat /tmp/custom.conf | grep ^'AutomaticLogin=' | cut -d'=' -f1`
if [ "$result" = "AutomaticLogin" ]; then
    sed -i 's/^AutomaticLogin=.*$/AutomaticLogin='$auto_login'/g' /tmp/custom.conf
else
    sed -i '/^\[daemon\]/a AutomaticLogin='$auto_login /tmp/custom.conf
fi


result=`cat /tmp/custom.conf | grep ^'AutomaticLoginEnable=' | cut -d'=' -f1`
if [ "$result" = "AutomaticLoginEnable" ]; then
    sed -i 's/^AutomaticLoginEnable=.*$/AutomaticLoginEnable=true/g' /tmp/custom.conf
else
    sed -i '/^\[daemon\]/a AutomaticLoginEnable=true' /tmp/custom.conf
fi

