#! /bin/bash
#
# Copyright © 2001 - 2012 Denis Salmanovich denis.salmanovich@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

[ -f /etc/denix-colors ] && . /etc/denix-colors

# Check if script runs under root
if ! [ "$(whoami)" = "root" ]; then
    echo "You have to run me with root user priveleges!"
    exit 1
fi

# Check the system version
[ -f /etc/fedora-release ] && system_version=`cat /etc/fedora-release | head -1 | awk '{print $3}'`
case ${system_version} in
    18|19)
    poptop_link="http://poptop.sourceforge.net/yum/stable/fc${system_version}/pptp-release-current.noarch.rpm"
    ;;

    *)
    echo "Unsupported system. Exiting."
    exit 1
    ;;
esac

# Install repository
if ! rpm -q "pptp-release" >/dev/null 2>&1; then
	echo "Poptop repository not installed!"
	echo "Trying to download and add it to the system..."
	if rpm -Uvh ${poptop_link} >/dev/null 2>&1; then
	    echo "poptop repo added to the system."
	else
	    echo "Download failed! Check internet connection and try again!"
	    exit 1
	fi
fi

# Install required packages
pk="pptpd firewalld"
for i in $pk; do
	if ! rpm -q $i >/dev/null 2>&1; then
		required_packages="$required_packages $i"
	fi
done

if ! [ "$required_packages" = "" ]; then
	echo "Some packages not found on your system. Trying to download and install..."
	if ! yum -y install $required_packages; then
		echo "Download failed! Check internet connection and try again!"
		exit 1
	else
		echo "Installation success!"
	fi
fi

# Ask for network device
while [ "${IFACE}" = "" ]; do
    IF_LIST=`ifconfig -a | sed 's/[: \t].*//;/^\(lo\|\)$/d'`
    if [[ -z "${IF_LIST}" ]]; then
	$color_BRed
	echo "No network adapters found."
	echo "Exiting..."
	$color_Off
	exit 1
    fi
    $color_Yellow
    echo
    echo "Found network adapters:"
    echo "~~~~~~~~~~~~~~~~~~~~~~~"
    for i in $IF_LIST; do
	if ! ip addr show ${i} | grep "inet " >/dev/null 2>&1; then
    	    IPADDR="<no address>"
	else
    	    IPADDR=`ifconfig ${i} | head -2 | tail -1 | awk '{print $2}' | cut -d":" -f2`
	fi
	echo "$i - $IPADDR"
    done
    $color_Off
    echo
    FOUND_IFACE=`ifconfig -a | sed 's/[: \t].*//;/^\(lo\|\)$/d' | head -1`
    $color_Cyan
    echo -n "What is your primary network interface [${FOUND_IFACE}]?"; read IFACE
    $color_Off
    if [ "${IFACE}" = "" ]; then
	IFACE="${FOUND_IFACE}"
    fi
    if ! ifconfig ${IFACE} >/dev/null 2>&1; then
	$color_Red
	echo "Error fetching network device: ${IFACE}"
	$color_Off
	IFACE=""
    fi
    if ! ip addr show ${IFACE} | grep "inet " >/dev/null 2>&1; then
	$color_Red
	echo "Error fetching IP address for device: ${IFACE}"
	$color_Off
	IFACE=""
    fi
done

# Stop service for installation and configuration
systemctl stop pptpd >/dev/null 2>&1

# Check, if /etc/ppp/options.pptp file already exists, then backup it
if [ -f /etc/ppp/options.pptp ]; then
    cp /etc/ppp/options.pptp /etc/ppp/options.pptp.back.`date +%Y%m%d%H%M`
fi

# Check, if /etc/pptpd.conf file already exists, then backup it
if [ -f /etc/pptpd.conf ]; then
    cp /etc/pptpd.conf /etc/pptpd.conf.back.`date +%Y%m%d%H%M`
fi

# Discovery system configuration
IPADDR=`ifconfig ${IFACE} | head -2 | tail -1 | awk '{print $2}' | cut -d":" -f2`
LOCAL_IP=`echo ${IPADDR} | awk -F. '{print $1"."$2"."$3".221"}'`
REMOTE_RANGE=`echo ${IPADDR} | awk -F. '{print $1"."$2"."$3".222-230"}'`

# Creating /etc/pptpd.conf config
cat > /etc/pptpd.conf << EOF
option /etc/ppp/options.pptp
logwtmp
localip ${LOCAL_IP}
remoteip ${REMOTE_RANGE}
EOF

# Creating /etc/ppp/options.pptp config
cat > /etc/ppp/options.pptp << EOF
name pptpd
refuse-pap
refuse-chap
refuse-mschap
require-mschap-v2
require-mppe-128
ms-dns ${LOCAL_IP}
ms-wins ${LOCAL_IP}
proxyarp
lock
nobsdcomp
novj
novjccomp
nologfd
EOF

# Check filewall ports
if ! firewall-cmd --permanent --query-port=1723/tcp; then
    $color_Red
    echo "The PPTP service port (1723/tcp) is closed in your firewall!"
    $color_Cyan
    echo -n "Do you want to open it now? (Y/n)?"; read USERINPUT
    $color_Off
    if [ "${USERINPUT}" = "" -o "${USERINPUT}" = "y" -o "${USERINPUT}" = "Y" ]; then
	firewall-cmd --permanent --add-port=1723/tcp
	firewall-cmd --reload
	$color_BGreen
	echo "The PPTP service port (1723/tcp) was opened in your firewall!!!"
	$color_Off
    else
	$color_BRed
	echo "The PPTP service port (1723/tcp) was not been opened in your firewall!!!"
	$color_Off
    fi
fi

# Enable daemon
systemctl enable pptpd >/dev/null 2>&1

# Start daemon
systemctl start pptpd >/dev/null 2>&1

# Create installation signature
if ! [ -d /var/lib/system-setup-tools ]; then
	install -d /var/lib/system-setup-tools
fi
echo "Install date: `date`" > /var/lib/system-setup-tools/pptpd

# Print info
$color_Purple
echo "Do not forget to open protocol 47/ip in your firewall!"
echo
echo "You have to add your remote users to /etc/ppp/chap-secrets:"
echo
echo "username   pptpd   password   *"
echo
echo
$color_BGreen
echo "Setup completed!"
$color_Off
