#! /bin/bash
#
# Copyright © 2001 - 2012 Denis Salmanovich denis.salmanovich@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

[ -f /etc/denix-colors ] && . /etc/denix-colors

# Check system version
[ -f /etc/fedora-release ] && system_ver=`cat /etc/fedora-release | head -1 | awk '{print $3}'`
if ! [ $system_ver = "21" -o $system_ver = "19" -o $system_ver = "20" ]; then
    $color_Red
    echo "Not supported platform!"
    echo "Exiting..."
    $color_Off
    exit 1
fi

# Check if script runs under root
if ! [ "$(whoami)" = "root" ]; then
    echo "You have to run me with root user priveleges!"
    exit 1
fi

# Install required packages
pk="httpd php php-pear php-mysql php-mbstring firewalld"
for i in $pk; do
	if ! rpm -q $i >/dev/null 2>&1; then
		required_packages="$required_packages $i"
	fi
done

if ! [ "$required_packages" = "" ]; then
	$color_Purple
	echo "Some packages not found on your system. Trying to download and install..."
	if ! yum -y install $required_packages; then
	    $color_BRed
	    echo "Download failed! Check internet connection and try again!"
	    $color_Off
	    exit 1
	else
	    $color_Green
	    echo "Installation success!"
	    $color_Off
	fi
fi

# Stop the services for installation
systemctl stop httpd >/dev/null 2>&1

# Create skeleton pub directory
if ! [ -f /etc/skel/.public_html ]; then
    install -m 710 -d /etc/skel/.public_html
fi

# Discovery system configuration
DOMAINNAME=`hostname`

# Check, if vhosts file already exists, then backup it
if [ -f /etc/httpd/conf.d/vhosts.conf ]; then
    cp /etc/httpd/conf.d/vhosts.conf /etc/httpd/conf.d/vhosts.conf.back.`date +%Y%m%d%H%M`
fi

# Check, if /etc/hosts file already exists, then backup it
if [ -f /etc/hosts ]; then
    cp /etc/hosts /etc/hosts.back.`date +%Y%m%d%H%M`
fi

# Create new hosts file
cat > /etc/hosts << EOF
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 ${DOMAINNAME}
EOF

# Make public_html directories for existing users (if exists)
if [ "$(ls -A /home)" ]; then
    for i in `ls -d /home/*`; do
	if [ -f $i/.bashrc ]; then
	    CUSER=`echo $i | cut -d/ -f3`
	    echo -n "Creating public_html directory for user: $CUSER... "
	    install -m 710 -d $i/.public_html
	    chown $CUSER:$CUSER $i/.public_html
	    echo "done."
	fi
    done
fi

# Enable UserDir mode
sed -i 's/^.*UserDir disabled$/#UserDir disabled/g' /etc/httpd/conf/httpd.conf

# Disable errors notifications
sed -i 's/^error_reporting.*$/error_reporting = E_ERROR/g' /etc/php.ini

# Switch short open tag On
sed -i 's/^short_open_tag = Off/short_open_tag = On/g' /etc/php.ini

# Create userdir configuration
cat > /etc/httpd/conf.d/userdir.conf << EOF
<IfModule mod_userdir.c>
    UserDir /home/*/.public_html
</IfModule>

<Directory /home/*/.public_html>
    Options Indexes FollowSymLinks Multiviews
    AllowOverride All
    Require all granted
</Directory>
EOF

# Add DeniX related configuration
cat > /etc/httpd/conf.d/denix.conf << EOF
ServerSignature Off
ServerTokens Prod
EOF

# Add apache optimization config for arm platfoms
sys_arch=$(uname -m)
if [ "${sys_arch:0:3}" = "arm" ]; then
    cat > /etc/httpd/conf.d/arm_optimization.conf << EOF
HostnameLookups      Off
TimeOut              150
KeepAlive            On
MaxKeepAliveRequests 50
KeepAliveTimeout     10
StartServers         2
MinSpareServers      2
MaxSpareServers      5
ServerLimit          128
MaxClients           128
MaxRequestsPerChild  500
EOF
fi

# Create noindex content
cat > /usr/share/httpd/noindex/index.html << EOF
<br>
<br>
<p align=center>Welcome to Linux server !!!</text>
<br>
<p align=center>~~~~~~~~~~~~~~~~~~~~~~~~~~~</text>
EOF

# Create virtual hosts configuration
cat > /etc/httpd/conf.d/vhosts.conf << EOF
ServerName ${DOMAINNAME}

<VirtualHost *:80>
    DocumentRoot /var/www/html
    ServerPath /html
    ServerName ${DOMAINNAME}
    ServerAlias ${DOMAINNAME}
    ServerAlias www.${DOMAINNAME}
</VirtualHost>
EOF

# Check filewall ports
if ! firewall-cmd --permanent --query-service=http; then
    $color_Red
    echo "The HTTP service port (80/tcp) is closed in your firewall!"
    $color_Cyan
    echo -n "Do you want to open it now? (Y/n)?"; read USERINPUT
    $color_Off
    if [ "${USERINPUT}" = "" -o "${USERINPUT}" = "y" -o "${USERINPUT}" = "Y" ]; then
	firewall-cmd --permanent --add-service=http
	firewall-cmd --reload
	$color_BGreen
	echo "The HTTP service port (80/tcp) was opened in your firewall!!!"
	$color_Off
    else
	$color_BRed
	echo "The HTTP service port (80/tcp) was not been opened in your firewall!!!"
	$color_Off
    fi
fi

# Enable daemons
systemctl enable httpd >/dev/null 2>&1

# Start daemons
systemctl start httpd >/dev/null 2>&1

# Create installation signature
if ! [ -d /var/lib/system-setup-tools ]; then
    install -d /var/lib/system-setup-tools
fi
echo "Install date: `date`" > /var/lib/system-setup-tools/httpd

$color_Purple
echo "Now you can setup the virtualhost with <system-setup-virtualhost> command!"
$color_BGreen
echo "Setup completed!"
$color_Off
