#! /bin/bash
#
# Copyright © 2001 - 2012 Denis Salmanovich denis.salmanovich@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

[ -f /etc/denix-colors ] && . /etc/denix-colors

# Check system version
[ -f /etc/fedora-release ] && system_ver=`cat /etc/fedora-release | head -1 | awk '{print $3}'`
if ! [ $system_ver = "18" -o $system_ver = "19" -o $system_ver = "20" ]; then
    $color_Red
    echo "Not supported platform!"
    echo "Exiting..."
    $color_Off
    exit 1
fi

# Check if script runs under root
if ! [ "$(whoami)" = "root" ]; then
    echo "You have to run me with root user priveleges!"
    exit 1
fi

# Set variable of configuration file
dovecot_config="/etc/dovecot/dovecot.conf"

# Stop the services for installation
systemctl stop dovecot >/dev/null 2>&1

# Install required packages
pk="dovecot firewalld"
for i in $pk; do
    if ! rpm -q $i >/dev/null 2>&1; then
	required_packages="$required_packages $i"
    fi
done

if ! [ "$required_packages" = "" ]; then
    $color_Purple
    echo "Some packages not found on your system. Trying to download and install..."
    if ! yum -y install $required_packages; then
        $color_BRed
        echo "Download failed! Check internet connection and try again!"
        $color_Off
        exit 1
    else
        $color_Green
        echo "Installation success!"
        $color_Off
    fi
fi

# Discovery system configuration
DOMAINNAME=`hostname`

# Check, if configuration file already exists, then backup it
if [ -f ${dovecot_config} ]; then
    cp ${dovecot_config} ${dovecot_config}.back.`date +%Y%m%d%H%M`
fi

# Create default configuration file
cat > ${dovecot_config} << EOF
auth_mechanisms = plain
disable_plaintext_auth = no
mail_location = maildir:~/.maildir
protocols = imap
ssl_cert = </etc/pki/dovecot/certs/ca.crt
ssl_key = </etc/pki/dovecot/private/ca.key

passdb {
    driver = pam
}

userdb {
    driver = passwd
}

EOF

# Check, if server certificate already exists, then backup it
if [ -f /etc/pki/dovecot/certs/ca.crt ]; then
    cp /etc/pki/dovecot/certs/ca.crt /etc/pki/dovecot/certs/ca.crt.back.`date +%Y%m%d%H%M`
fi

# Check, if server key already exists, then backup it
if [ -f /etc/pki/dovecot/private/ca.key ]; then
    cp /etc/pki/dovecot/private/ca.key /etc/pki/dovecot/private/ca.key.back.`date +%Y%m%d%H%M`
fi

# Check, if server csr already exists, then backup it
if [ -f /etc/pki/dovecot/private/ca.csr ]; then
    cp /etc/pki/dovecot/private/ca.csr /etc/pki/dovecot/private/ca.csr.back.`date +%Y%m%d%H%M`
fi

# Generate the server key
echo "Generating new server key..."
openssl genrsa -out /etc/pki/dovecot/private/ca.key 1024 >/dev/null 2>&1
chmod 600 /etc/pki/dovecot/private/ca.key

# Generate the server certificate sign request
echo "Generating new server sign request..."
openssl req -new -key /etc/pki/dovecot/private/ca.key -out /etc/pki/dovecot/private/ca.csr -batch >/dev/null 2>&1
chmod 600 /etc/pki/dovecot/private/ca.csr

# Generate th server self signed certificate
echo "Generating new server self signed certificate..."
openssl x509 -req -days 365 -in /etc/pki/dovecot/private/ca.csr -signkey /etc/pki/dovecot/private/ca.key -out /etc/pki/dovecot/certs/ca.crt >/dev/null 2>&1
chmod 600 /etc/pki/dovecot/certs/ca.crt

# Check filewall ports
if ! firewall-cmd --permanent --query-port=143/tcp; then
    $color_Red
    echo "The IMAP service port (143/tcp) is closed in your firewall!"
    $color_Cyan
    echo -n "Do you want to open it now? (Y/n)?"; read USERINPUT
    $color_Off
    if [ "${USERINPUT}" = "" -o "${USERINPUT}" = "y" -o "${USERINPUT}" = "Y" ]; then
	firewall-cmd --permanent --add-port=143/tcp
	firewall-cmd --reload
	$color_BGreen
	echo "The IMAP service port (143/tcp) was opened in your firewall!!!"
	$color_Off
    else
	$color_BRed
	echo "The IMAP service port (143/tcp) was not been opened in your firewall!!!"
	$color_Off
    fi
fi

# Enable dovecot daemon
systemctl enable dovecot >/dev/null 2>&1

# Start dovecot server
systemctl start dovecot >/dev/null 2>&1

# Create installation signature
if ! [ -d /var/lib/system-setup-tools ]; then
    install -d /var/lib/system-setup-tools
fi
echo "Install date: `date`" > /var/lib/system-setup-tools/dovecot

$color_BGreen
echo "Setup completed!"
$color_Off
