#! /bin/bash
#
# Copyright © 2001 - 2012 Denis Salmanovich denis.salmanovich@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

[ -f /etc/denix-colors ] && . /etc/denix-colors

# Check system version
[ -f /etc/fedora-release ] && system_ver=`cat /etc/fedora-release | head -1 | awk '{print $3}'`
if ! [ $system_ver = "18" -o $system_ver = "19" -o $system_ver = "20" ]; then
    $color_Red
    echo "Not supported platform!"
    echo "Exiting..."
    $color_Off
    exit 1
fi

# Check if script runs under root
if ! [ "$(whoami)" = "root" ]; then
    echo "You have to run me with root user priveleges!"
    exit 1
fi

# Install required packages
pk="bind firewalld bind-utils"
for i in $pk; do
    if ! rpm -q $i >/dev/null 2>&1; then
	required_packages="$required_packages $i"
    fi
done

if ! [ "$required_packages" = "" ]; then
    $color_Purple
    echo "Some packages not found on your system. Trying to download and install..."
    if ! yum -y install $required_packages; then
	$color_BRed
	echo "Download failed! Check internet connection and try again!"
	$color_Off
	exit 1
    else
        $color_Green
        echo "Installation success!"
        $color_Off
    fi
fi

# Ask for network device
while [ "${IFACE}" = "" ]; do
    IF_LIST=`ifconfig -a | sed 's/[: \t].*//;/^\(lo\|\)$/d'`
    if [[ -z "${IF_LIST}" ]]; then
	$color_BRed
	echo "No network adapters found."
	echo "Exiting..."
	$color_Off
	exit 1
    fi
    $color_Yellow
    echo
    echo "Found network adapters:"
    echo "~~~~~~~~~~~~~~~~~~~~~~~"
    for i in $IF_LIST; do
	if ! ip addr show ${i} | grep "inet " >/dev/null 2>&1; then
    	    IPADDR="<no address>"
	else
    	    IPADDR=`ifconfig ${i} | head -2 | tail -1 | awk '{print $2}' | cut -d":" -f2`
	fi
	echo "$i - $IPADDR"
    done
    $color_Off
    echo
    FOUND_IFACE=`ifconfig -a | sed 's/[: \t].*//;/^\(lo\|\)$/d' | head -1`
    $color_Cyan
    echo -n "What is your primary network interface [${FOUND_IFACE}]?"; read IFACE
    $color_Off
    if [ "${IFACE}" = "" ]; then
	IFACE="${FOUND_IFACE}"
    fi
    if ! ifconfig ${IFACE} >/dev/null 2>&1; then
	$color_Red
	echo "Error fetching network device: ${IFACE}"
	$color_Off
	IFACE=""
    fi
    if ! ip addr show ${IFACE} | grep "inet " >/dev/null 2>&1; then
	$color_Red
	echo "Error fetching IP address for device: ${IFACE}"
	$color_Off
	IFACE=""
    fi
done

# Ask for DNS forwarders
echo -n "Do you want to setup DNS forwarders [y/N]?"; read USERINPUT
if [ "${USERINPUT}" = "y" -o "${USERINPUT}" = "Y" ]; then
    while [ "${FORWARDER_DNS1}" = "" ]; do
	echo -n "Enter the first DNS forwarder: "; read DNS1
	echo -n "Checking DNS server <$DNS1>... "
	if ! ping -c1 $DNS1 >/dev/null 2>&1; then
	    echo "connection failed!"
	    echo "The DNS <$DNS1> is not responding! Please check your input and try again."
	    FORWARDER_DNS1=""
	else
	    echo "ok"
	    FORWARDER_DNS1=$DNS1
	fi
    done
    while [ "${FORWARDER_DNS2}" = "" ]; do
	echo -n "Enter the second DNS forwarder: "; read DNS2
	echo -n "Checking DNS server <$DNS2>... "
	if ! ping -c1 $DNS2 >/dev/null 2>&1; then
	    echo "connection failed!"
	    echo "The DNS <$DNS2> is not responding! Please check your input and try again."
	    FORWARDER_DNS2=""
	else
	    echo "ok"
	    FORWARDER_DNS2=$DNS2
	fi
    done
    FORWARDERS="forwarders { $FORWARDER_DNS1; $FORWARDER_DNS2; };"
else
    FORWARDERS=""
fi

# Discovery system configuration
IPADDR=`ifconfig ${IFACE} | head -2 | tail -1 | awk '{print $2}' | cut -d":" -f2`
NETMASK=`ifconfig ${IFACE} | head -2 | tail -1 | awk '{print $4}' | cut -d":" -f2`
NETWORK=`echo ${IPADDR} | awk -F. '{print $1"."$2"."$3".0"}'`
DOMAINNAME=`hostname`
ARPA=`echo ${IPADDR} | awk -F. '{print $3"."$2"."$1".in-addr.arpa"}'`
LAST_SEG=`echo ${IPADDR} | cut -d. -f4`
MASK=`ipcalc ${NETWORK} ${NETMASK} -p | cut -d= -f2`


# Stop the service for installation
systemctl stop named >/dev/null 2>&1

# Backup old configuration file
if [ -f /etc/named.conf ]; then
    mv /etc/named.conf /etc/named.conf.back.`date +%Y%m%d%H%M`
fi

# Backup old rndc key
if [ -f /etc/rndc.key ]; then
    mv /etc/rndc.key /etc/rndc.key.back.`date +%Y%m%d%H%M`
fi

# Generate new rndc key
echo "Generating new rndc key..."
rndc-confgen -ac /etc/rndc.key
chown named:named /etc/rndc.key

# Creating new configuration file
cat > /etc/named.conf << EOF
options {
	recursion yes;
	dnssec-enable yes;
	dnssec-validation yes;
	dnssec-lookaside auto;
	bindkeys-file "/etc/named.iscdlv.key";
	managed-keys-directory "/var/named/dynamic";
	directory "/var/named";
	dump-file "/var/named/data/cache_dump.db";
	statistics-file "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	$FORWARDERS
	allow-query {
		any;
	};
};

include "/etc/rndc.key";

controls {
	inet * allow { 127.0.0.1; ${IPADDR}; } keys { rndc-key; };
};

logging {
	channel default_debug {
		file "data/named.run";
		severity dynamic;
	};
};

view "internal" {
	match-clients {
		${NETWORK}/${MASK};
	};

	zone "." IN {
		type hint;
		file "named.ca";
	};

	include "/etc/named.rfc1912.zones";
	include "/etc/named.root.key";
	include "masters/internal.zones";
	include "slaves/internal.zones";
	include "reverse/internal.zones";
};

view "external" {
	match-clients {
		any;
		localhost;
	};

	zone "." IN {
		type hint;
		file "named.ca";
	};

	include "/etc/named.rfc1912.zones";
	include "/etc/named.root.key";
	include "masters/external.zones";
	include "slaves/external.zones";
	include "reverse/external.zones";
};
EOF

chown root:named /etc/named.conf
chmod 640 /etc/named.conf

# Create rfc1912 zones
cat > /etc/named.rfc1912.zones << EOF
zone "localhost.localdomain" IN {
    type master;
    file "named.localhost";
    allow-update { none; };
};
    
zone "localhost" IN {
    type master;
    file "named.localhost";
    allow-update { none; };
};

zone "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa" IN {
    type master;
    file "named.loopback";
    allow-update { none; };
};
    
zone "1.0.0.127.in-addr.arpa" IN {
    type master;
    file "named.loopback";
    allow-update { none; };
};

zone "0.in-addr.arpa" IN {
    type master;
    file "named.empty";
    allow-update { none; };
};
EOF

chown root:named /etc/named.rfc1912.zones
chmod 640 /etc/named.rfc1912.zones

# Backup old named database
if [ -e /var/named ]; then
	mv -f /var/named /var/named.back.`date +%Y%m%d%H%M`
fi

# Install new database directories
install -m 770 -d /var/named/{masters,reverse,slaves,data,dynamic}
chown root:named /var/named

install -m 770 -d /var/named/masters/{internal,external}
chown -R named:named /var/named/masters
install -m 770 -d /var/named/reverse/{internal,external}
chown -R named:named /var/named/reverse
install -m 770 -d /var/named/slaves/{internal,external}
chown -R named:named /var/named/slaves
chown -R named:named /var/named/data
chown -R named:named /var/named/dynamic

# Create zone files
touch /var/named/reverse/external.zones
touch /var/named/slaves/internal.zones
touch /var/named/slaves/external.zones

chown named:named /var/named/reverse/external.zones
chown named:named /var/named/slaves/internal.zones
chown named:named /var/named/slaves/external.zones

chmod 640 /var/named/reverse/external.zones
chmod 640 /var/named/slaves/internal.zones
chmod 640 /var/named/slaves/external.zones

# Create named.ca
touch /var/named/named.ca
chown root:named /var/named/named.ca
chmod 640 /var/named/named.ca
cat > /var/named/named.ca << EOF
;; ANSWER SECTION:
.			518400	IN	NS	b.root-servers.net.
.			518400	IN	NS	c.root-servers.net.
.			518400	IN	NS	i.root-servers.net.
.			518400	IN	NS	m.root-servers.net.
.			518400	IN	NS	e.root-servers.net.
.			518400	IN	NS	l.root-servers.net.
.			518400	IN	NS	a.root-servers.net.
.			518400	IN	NS	f.root-servers.net.
.			518400	IN	NS	d.root-servers.net.
.			518400	IN	NS	j.root-servers.net.
.			518400	IN	NS	h.root-servers.net.
.			518400	IN	NS	g.root-servers.net.
.			518400	IN	NS	k.root-servers.net.

;; ADDITIONAL SECTION:
b.root-servers.net.	3600000	IN	A	192.228.79.201
c.root-servers.net.	3600000	IN	A	192.33.4.12
i.root-servers.net.	3600000	IN	AAAA	2001:7fe::53
i.root-servers.net.	3600000	IN	A	192.36.148.17
m.root-servers.net.	3600000	IN	AAAA	2001:dc3::35
m.root-servers.net.	3600000	IN	A	202.12.27.33
e.root-servers.net.	3600000	IN	A	192.203.230.10
l.root-servers.net.	3600000	IN	AAAA	2001:500:3::42
l.root-servers.net.	3600000	IN	A	199.7.83.42
a.root-servers.net.	3600000	IN	AAAA	2001:503:ba3e::2:30
a.root-servers.net.	3600000	IN	A	198.41.0.4
f.root-servers.net.	3600000	IN	AAAA	2001:500:2f::f
f.root-servers.net.	3600000	IN	A	192.5.5.241
d.root-servers.net.	3600000	IN	AAAA	2001:500:2d::d
d.root-servers.net.	3600000	IN	A	199.7.91.13
j.root-servers.net.	3600000	IN	AAAA	2001:503:c27::2:30
j.root-servers.net.	3600000	IN	A	192.58.128.30
h.root-servers.net.	3600000	IN	AAAA	2001:500:1::803f:235
h.root-servers.net.	3600000	IN	A	128.63.2.53
g.root-servers.net.	3600000	IN	A	192.112.36.4
k.root-servers.net.	3600000	IN	AAAA	2001:7fd::1
k.root-servers.net.	3600000	IN	A	193.0.14.129
EOF

# Create named.localhost
cat > /var/named/named.localhost << EOF
\$TTL 1D
@	IN SOA	@ rname.invalid. (
					0	; serial
					1D	; refresh
					1H	; retry
					1W	; expire
					3H )	; minimum
	NS	@
	A	127.0.0.1
	AAAA	::1
EOF
chown root:named /var/named/named.localhost
chmod 640 /var/named/named.localhost

# Create named.loopback
cat > /var/named/named.loopback << EOF
\$TTL 1D
@	IN SOA	@ rname.invalid. (
					0	; serial
					1D	; refresh
					1H	; retry
					1W	; expire
					3H )	; minimum
	NS	@
	A	127.0.0.1
	AAAA	::1
	PTR	localhost.
EOF
chown root:named /var/named/named.loopback
chmod 640 /var/named/named.loopback

# Create named.empty
cat > /var/named/named.empty << EOF
\$TTL 3H
@	IN SOA	@ rname.invalid. (
					0	; serial
					1D	; refresh
					1H	; retry
					1W	; expire
					3H )	; minimum
	NS	@
	A	127.0.0.1
	AAAA	::1
EOF
chown root:named /var/named/named.empty
chmod 640 /var/named/named.empty

cat > /var/named/masters/internal.zones << EOF
zone "${DOMAINNAME}" IN {
    type master;
    file "masters/internal/${DOMAINNAME}";
    allow-update { key rndc-key; };
    allow-transfer { none; };
};
EOF
chown named:named /var/named/masters/internal.zones
chmod 640 /var/named/masters/internal.zones

cat > /var/named/masters/internal/${DOMAINNAME} << EOF
\$ORIGIN .
\$TTL 300	; 5 minutes
${DOMAINNAME}		IN SOA	ns.${DOMAINNAME}. hostmaster.${DOMAINNAME}. (
				1          ; serial
                                300        ; refresh (5 minutes)
                                300        ; retry (5 minutes)
                                300        ; expire (5 minutes)
                                300        ; minimum (5 minutes)
                                )
                        NS      ns.${DOMAINNAME}.
                        A       ${IPADDR}
                        MX      10 ${DOMAINNAME}.
\$ORIGIN ${DOMAINNAME}.
ns                      A       ${IPADDR}
mail			A	${IPADDR}
www			A	${IPADDR}
EOF
chown named:named /var/named/masters/internal/${DOMAINNAME}

cat > /var/named/masters/external.zones << EOF
zone "${DOMAINNAME}" IN {
    type master;
    file "masters/external/${DOMAINNAME}";
    allow-update { key rndc-key; };
    allow-transfer { none; };
};
EOF
chown named:named /var/named/masters/external.zones
chmod 640 /var/named/masters/external.zones

cat > /var/named/masters/external/${DOMAINNAME} << EOF
\$ORIGIN .
\$TTL 300	; 5 minutes
${DOMAINNAME}		IN SOA	ns.${DOMAINNAME}. hostmaster.${DOMAINNAME}. (
				1          ; serial
                                300        ; refresh (5 minutes)
                                300        ; retry (5 minutes)
                                300        ; expire (5 minutes)
                                300        ; minimum (5 minutes)
                                )
                        NS      ns.${DOMAINNAME}.
                        A       ${IPADDR}
                        MX      10 ${DOMAINNAME}.
\$ORIGIN ${DOMAINNAME}.
ns                      A       ${IPADDR}
mail			A	${IPADDR}
www			A	${IPADDR}
EOF
chown named:named /var/named/masters/external/${DOMAINNAME}


cat > /var/named/reverse/internal.zones << EOF
zone "${ARPA}" IN {
    type master;
    file "reverse/internal/${ARPA}";
    allow-update { key rndc-key; };
    allow-transfer { none; };
};
EOF
chown named:named /var/named/reverse/internal.zones
chmod 640 /var/named/reverse/internal.zones

cat > /var/named/reverse/internal/${ARPA} << EOF
\$TTL 300        ; 5 minutes
${ARPA}.		IN SOA  ${DOMAINNAME}. hostmaster.${DOMAINNAME}. (
                                1          ; serial
                                3600       ; refresh (1 hour)
                                1800       ; retry (30 minutes)
                                604800     ; expire (1 week)
                                86400      ; minimum (1 day)
                                )
                        NS      ${DOMAINNAME}.
${LAST_SEG}		PTR	${DOMAINNAME}.
EOF
chown named:named /var/named/reverse/internal/${ARPA}

cat > /var/named/reverse/external.zones << EOF
zone "${ARPA}" IN {
    type master;
    file "reverse/external/${ARPA}";
    allow-update { key rndc-key; };
    allow-transfer { none; };
};
EOF
chown named:named /var/named/reverse/external.zones
chmod 640 /var/named/reverse/external.zones

cat > /var/named/reverse/external/${ARPA} << EOF
\$TTL 300        ; 5 minutes
${ARPA}.		IN SOA  ${DOMAINNAME}. hostmaster.${DOMAINNAME}. (
                                1          ; serial
                                3600       ; refresh (1 hour)
                                1800       ; retry (30 minutes)
                                604800     ; expire (1 week)
                                86400      ; minimum (1 day)
                                )
                        NS      ${DOMAINNAME}.
${LAST_SEG}		PTR	${DOMAINNAME}.
EOF
chown named:named /var/named/reverse/external/${ARPA}

# Add local dns server to resolv.conf
if [ "${FORWARDERS}" = "" ]; then
    cat > /etc/resolv.conf << EOF
search ${DOMAINNAME}
nameserver ${IPADDR}
nameserver 127.0.0.1
EOF
else
    cat > /etc/resolv.conf << EOF
search ${DOMAINNAME}
nameserver ${FORWARDER_DNS1}
nameserver ${FORWARDER_DNS2}
nameserver ${IPADDR}
nameserver 127.0.0.1
EOF
fi

# Disable IPv6
echo 'OPTIONS="-4"' > /etc/sysconfig/named

# Check filewall ports
if ! firewall-cmd --permanent --query-service=dns; then
    $color_Red
    echo "The DNS service port (53/tcp) is closed in your firewall!"
    $color_Cyan
    echo -n "Do you want to open it now? (Y/n)?"; read USERINPUT
    $color_Off
    if [ "${USERINPUT}" = "" -o "${USERINPUT}" = "y" -o "${USERINPUT}" = "Y" ]; then
	firewall-cmd --permanent --add-service=dns
	firewall-cmd --reload
	$color_BGreen
	echo "The DNS service port (53/tcp) was opened in your firewall!!!"
	$color_Off
    else
	$color_BRed
	echo "The DNS service port (53/tcp) was not been opened in your firewall!!!"
	$color_Off
    fi
fi

# Enable dns server daemon
echo "Enabling named server..."
systemctl enable named >/dev/null 2>&1

# Start dns server
echo "Starting named server..."
systemctl start named >/dev/null 2>&1

# Create installation signature
if ! [ -d /var/lib/system-setup-tools ]; then
	install -d /var/lib/system-setup-tools
fi
echo "Install date: `date`" > /var/lib/system-setup-tools/named

$color_BGreen
echo "Setup completed!"
$color_Off
