#! /bin/bash
#
# Copyright © 2001 - 2012 Denis Salmanovich denis.salmanovich@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

[ -f /etc/denix-colors ] && . /etc/denix-colors

# Check system version
[ -f /etc/fedora-release ] && system_ver=`cat /etc/fedora-release | head -1 | awk '{print $3}'`
if ! [ $system_ver = "17" -o $system_ver = "18" -o $system_ver = "19" ]; then
    $color_Red
    echo "Not supported platform!"
    echo "Exiting..."
    $color_Off
    exit 1
fi

# Check if script runs under root
if ! [ "$(whoami)" = "root" ]; then
    echo "You have to run me with root user priveleges!"
    exit 1
fi

# Install proftpd packages
pk="proftpd firewalld"
for i in $pk; do
    if ! rpm -q $i >/dev/null 2>&1; then
	required_packages="$required_packages $i"
    fi
done

if ! [ "$required_packages" = "" ]; then
    $color_Purple
    echo "Some packages not found on your system. Trying to download and install..."
    if ! yum -y install $required_packages; then
        $color_BRed
        echo "Download failed! Check internet connection and try again!"
        $color_Off
        exit 1
    else
        $color_Green
        echo "Installation success!"
        $color_Off
    fi
fi

# Create pub directory for default users
if ! [ -f /etc/skel/.public_html ]; then
    install -m 710 -d /etc/skel/.public_html
fi

# Discovery system configuration
DOMAINNAME=`hostname`

# Check, if configuration file already exists, then backup it
if [ -f /etc/proftpd.conf ]; then
    cp /etc/proftpd.conf /etc/proftpd.conf.back.`date +%Y%m%d%H%M`
fi

# Make pub directories for existing users
$color_Green
for i in `ls -d /home/*`; do
    if [ -f $i/.bashrc ]; then
	CUSER=`echo $i | cut -d/ -f3`
	echo -n "Creating pub directory for user: $CUSER... "
	install -m 710 -d $i/.public_html
	chown $CUSER:$CUSER $i/.public_html
	echo "done."
    fi
done
$color_Off

# Stop the services for installation
systemctl stop proftpd >/dev/null 2>&1

cat > /etc/proftpd.conf << EOF
ServerName			"ProFTPD server"
ServerIdent			off
ServerAdmin			root@$DOMAINNAME
ServerType			standalone
DefaultServer			on
AccessGrantMsg			"User %u logged in."
#DisplayConnect			/etc/ftpissue
#DisplayLogin			/etc/ftpmotd
#DisplayGoAway			/etc/ftpgoaway
DeferWelcome			off

DefaultRoot			~/.public_html !adm
#AuthPAMConfig			proftpd
#AuthOrder			mod_auth_pam.c* mod_auth_unix.c
IdentLookups			off
UseReverseDNS			off
Port				21
Umask				022
RootLogin			off
MaxLoginAttempts		3
AllowRetrieveRestart		on
AllowStoreRestart		on
MaxInstances			20
User				nobody
Group				nobody
UseSendfile			no
ScoreboardFile			/var/run/proftpd.score

<Global>
  AllowOverwrite		yes
  <Limit ALL SITE_CHMOD>
    AllowAll
  </Limit>
</Global>

LogFormat			default	"%h %l %u %t \"%r\" %s %b"
LogFormat			auth	"%v [%P] %h %t \"%r\" %s"
EOF

# Check filewall ports
if ! firewall-cmd --permanent --query-service=ftp; then
    $color_Red
    echo "The FTP service port (21/tcp) is closed in your firewall!"
    $color_Cyan
    echo -n "Do you want to open it now? (Y/n)?"; read USERINPUT
    $color_Off
    if [ "${USERINPUT}" = "" -o "${USERINPUT}" = "y" -o "${USERINPUT}" = "Y" ]; then
	firewall-cmd --permanent --add-service=ftp
	firewall-cmd --reload
	$color_BGreen
	echo "The FTP service port (21/tcp) was opened in your firewall!!!"
	$color_Off
    else
	$color_BRed
	echo "The FTP service port (21/tcp) was not been opened in your firewall!!!"
	$color_Off
    fi
fi

# Enable proftpd daemon
systemctl enable proftpd >/dev/null 2>&1

# Start proftpd server
systemctl start proftpd >/dev/null 2>&1

# Create installation signature
if ! [ -d /var/lib/system-setup-tools ]; then
    install -d /var/lib/system-setup-tools
fi
echo "Install date: `date`" > /var/lib/system-setup-tools/proftpd

$color_BGreen
echo "Setup completed!"
$color_Off
